### ISSUE TITLE
Update tutorial in a Kubeflow way?

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/machine-learning-using-k8s#14]
I notice some of examples are for generic purpose like how to deploy Jupyter notebook, enable TensorBoard and also serving part.  On the contrary, as Kubeflow community grows fast, these components are included in the latest kubeflow suite.  I want to update these tutorials in a kubeflow way and I think it will help customers better leverage entire ML pipeline on EKS. 

What do you think?

**Comment by Jeffwan** [comment]
@arun-gupta  @gautamkmr

**Comment by goswamig** [comment]
+1 to idea. I am glad you are thinking this way. 
Training part I've done using kubeflow.  I am currently working on inference part. 

Definitely we should translate all example using kubeflow.

**Comment by arun-gupta** [comment]
+1 on making sure all examples work the kubeflow way.

// @aronchick would like it

**Comment by Jeffwan** [comment]
Thanks for the feedbacks. Will do soon. Long term goal is to add more AWS examples in upstream kubeflow community.

**Comment by Jeffwan** [comment]
Working in progress and will send out PR by next week.

**Comment by Jeffwan** [comment]
PR is merged and I can close this Issue
